### ISSUE TITLE
App crashed in android 5.1 (genymotion emulator) 

### ISSUE THREAD

**Issue by maxtat3** [maxtat3/radiocomp-intcom-android#21]
App started , upload json pricelist, do recorded in sqlite DB and ... crashed .

Process: edu.sintez.intcomapp.app, PID: 2077
    android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
            at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
            at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
            at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
            at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
            at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
            at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)
            at edu.sintez.intcomapp.app.db.DBHandlerImpl.getRecord(DBHandlerImpl.java:196)
            at edu.sintez.intcomapp.app.db.PriceListEngine.formingItems(PriceListEngine.java:158)
            at edu.sintez.intcomapp.app.db.PriceListEngine.access$500(PriceListEngine.java:32)
            at edu.sintez.intcomapp.app.db.PriceListEngine$FetchDB.onPostExecute(PriceListEngine.java:139)
            at edu.sintez.intcomapp.app.db.PriceListEngine$FetchDB.onPostExecute(PriceListEngine.java:107)
            at android.os.AsyncTask.finish(AsyncTask.java:636)

Filed in method 
if (cursor != null){
	cursor.moveToFirst();
}

**Comment by maxtat3** [comment]
Fixed. For detail see commit dc7c2c5396adf3765c84369df32beb938abd77ca
